Refactor/about-us
Dwarves-of-the-War-of-Horns/e-commerce pull request #101
Opened 2023-09-18 16:02 UTC by ashtotakoe

##### Link to Jira task
NO-JIRA
##### What kind of change does this PR introduce?

- [x] Bug fix
- [ ] Feature/change request
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build or CI related changes
- [ ] Other (include details)

##### What has changed?
- minor info changes
- add missing collaborator

##### Other information
- None

2023-09-18 16:03 UTC, ADyBaH approved these changes

2023-09-18 16:38 UTC, DeePenguin requested changes
We agreed to add info about our mentor in separate block, which also was supposed to include general information about our team and working process

2023-09-19 10:46 UTC, DeePenguin requested changes

2023-09-19 14:04 UTC, ashtotakoe commented on src/app/about/about-page.component.html
> +  <h2 class="header tui-text_h4">Our team</h2>
fixed

2023-09-19 14:19 UTC, ashtotakoe commented on src/app/about/components/general-info/general-info.component.html
done!

2023-09-19 14:20 UTC, ashtotakoe commented on src/app/about/components/general-info/general-info.component.ts
> +  styleUrls: ['./general-info.component.scss'],
done!

2023-09-19 14:50 UTC, DeePenguin approved these changes

2023-09-19 15:05 UTC, ADyBaH approved these changes

2023-09-19 15:06 UTC, merged